"""add refresh_tokens table

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-29

Adds revocable refresh token storage for the Auth module (Module 2).
See app/models/auth.py for the full reasoning on why refresh tokens are
tracked in the database (to support logout/revocation) while access
tokens are not.

Note: the autogenerated version of this migration also proposed dropping
every hand-added performance index from migration 0001. That's a false
positive -- those indexes were added directly via op.create_index() in
migration 0001 rather than declared as Index() objects on the SQLAlchemy
models, so Alembic's model-vs-database diff doesn't see them as
"belonging" to the schema and assumes they're drift to be removed. They
are intentional and have been left untouched here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("idx_refresh_tokens_user", "refresh_tokens", ["user_id"])
    op.create_index("idx_refresh_tokens_hash", "refresh_tokens", ["token_hash"])


def downgrade() -> None:
    op.drop_index("idx_refresh_tokens_hash", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_user", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
